version: "3.8"

services:
  app:
    build:
      dockerfile: api/Dockerfile
      context: .
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - PORT=8000
    env_file:
      - .env
    command: sh -c "prisma migrate deploy && uvicorn main:api --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - ./api:/app
      - ./prisma:/app/prisma
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
  # redis:
  #   image: redis:latest
  #   ports:
  #     - "6379:6379"
  # qdrant:
  #   image: qdrant/qdrant:latest
  #   ports:
  #     - "6333:6333"
  ngrok:
    image: wernight/ngrok
    env_file:
      - .env
    ports:
      - "4040:4040"
    depends_on:
      - app
    command: ngrok http app:8000 --region=eu --authtoken=${NGROK_AUTH} --log=stdout
